<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PO3T4V3" failures="6" tests="19" name="craftBetAutomation" time="167.558" errors="0" timestamp="2022-07-08T11:13:34 AMT">
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLabelsPresenceVerification_Test" time="0.201"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogoPresenceVerification_Test" time="0.045"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpCloseButtonFunctionality_Test" time="0.807"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpEyeButtonFunctionality_Test" time="0.668"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpRememberMeLabelClickAbility_Test" time="0.522"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpCheckBoxClickAbility_Test" time="0.476"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpForgotPasswordLink_Test" time="0.264"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpSignUpLink_Test" time="0.304"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInPositiveTest" time="2.06"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="10.375"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="2.2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testCases.LoginPopUpTest.loginPopUpLogInNegativeTest1(LoginPopUpTest.java:188)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginPopUpLogInNegativeTest1 -->
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="2.229">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testCases.LoginPopUpTest.loginPopUpLogInNegativeTest1(LoginPopUpTest.java:188)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginPopUpLogInNegativeTest1 -->
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="10.46"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="2.21">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testCases.LoginPopUpTest.loginPopUpLogInNegativeTest1(LoginPopUpTest.java:188)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginPopUpLogInNegativeTest1 -->
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="2.386">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testCases.LoginPopUpTest.loginPopUpLogInNegativeTest1(LoginPopUpTest.java:188)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginPopUpLogInNegativeTest1 -->
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="2.144">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testCases.LoginPopUpTest.loginPopUpLogInNegativeTest1(LoginPopUpTest.java:188)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginPopUpLogInNegativeTest1 -->
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpLogInNegativeTest1" time="0.164">
    <failure type="org.openqa.selenium.ElementClickInterceptedException" message="Element &amp;lt;button class=&amp;quot;craft_btn login_btn -btn not_active&amp;quot; type=&amp;quot;submit&amp;quot;&amp;gt; is not clickable at point (960,647) because another element &amp;lt;div class=&amp;quot;form_field&amp;quot;&amp;gt; obscures it
Build info: version: &amp;apos;4.2.1&amp;apos;, revision: &amp;apos;ac4d0fdd4a&amp;apos;
System info: host: &amp;apos;DESKTOP-PO3T4V3&amp;apos;, ip: &amp;apos;10.50.17.112&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.2&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [79273788-0d7f-4191-b564-680e92fefe8d, clickElement {id=782406c1-b896-40b9-8ad4-1ceccbc11053}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 101.0, moz:accessibilityChecks: false, moz:buildID: 20220526203855, moz:debuggerAddress: localhost:64920, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 15092, moz:profile: C:\Users\NERSES~1\AppData\L..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:64920/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Element: [[FirefoxDriver: firefox on WINDOWS (79273788-0d7f-4191-b564-680e92fefe8d)] -&amp;gt; xpath: //button[contains(text(),&amp;apos; Log In &amp;apos;) and @type=&amp;apos;submit&amp;apos;]]
Session ID: 79273788-0d7f-4191-b564-680e92fefe8d">
      <![CDATA[org.openqa.selenium.ElementClickInterceptedException: Element <button class="craft_btn login_btn -btn not_active" type="submit"> is not clickable at point (960,647) because another element <div class="form_field"> obscures it
Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
System info: host: 'DESKTOP-PO3T4V3', ip: '10.50.17.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [79273788-0d7f-4191-b564-680e92fefe8d, clickElement {id=782406c1-b896-40b9-8ad4-1ceccbc11053}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 101.0, moz:accessibilityChecks: false, moz:buildID: 20220526203855, moz:debuggerAddress: localhost:64920, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 15092, moz:profile: C:\Users\NERSES~1\AppData\L..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), se:cdp: ws://localhost:64920/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Element: [[FirefoxDriver: firefox on WINDOWS (79273788-0d7f-4191-b564-680e92fefe8d)] -> xpath: //button[contains(text(),' Log In ') and @type='submit']]
Session ID: 79273788-0d7f-4191-b564-680e92fefe8d
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:78)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at jdk.proxy2/jdk.proxy2.$Proxy22.click(Unknown Source)
at pageObjects.BasePage.clickOnElementIfClickable(BasePage.java:90)
at pageObjects.CraftBet_Login_PopUp_Page.clickLoginPopUpLogInButton(CraftBet_Login_PopUp_Page.java:179)
at testCases.LoginPopUpTest.loginPopUpLogInNegativeTest1(LoginPopUpTest.java:185)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginPopUpLogInNegativeTest1 -->
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpErrorMessageValidationInvalidUsername" time="1.406"/>
  <testcase classname="testCases.LoginPopUpTest" name="loginPopUpErrorMessageValidationInvalidPassword" time="1.407"/>
</testsuite> <!-- craftBetAutomation -->
